### ISSUE TITLE
Implement Firebase authorization

### ISSUE THREAD

**Issue by chayesss** [chayesss/knowledge-quest#4]
Need to be able to implement the Firebase SSO authorization to the angular project.

Deliverables:
- be able to sign in with google or other SSO providers

**Comment by Fatima2324** [comment]
Will be adding information to this by tomorrow or Thursday

**Comment by Fatima2324** [comment]
Firebase offers two ways to handle user authentication:

FirebaseUI Auth: A pre-built, customizable UI for handling sign-in/sign-up forms, which makes setup quicker and easier because most of the work is done for you.

Firebase SDK Auth: A set of tools that let you build your own custom authentication flows. This gives you more control but requires more coding effort.

In simple terms, Firebase SDK Auth is the toolkit that helps you connect your app to Firebase’s authentication system, giving you flexibility to build the experience you want.

You aren’t choosing between FirebaseUI and Firebase SDK; rather, Firebase SDK is the foundation that supports both options. Firebase SDK Auth is great if you want more customization and control.

Your preference for Firebase SDK Auth makes sense if you want more flexibility in how authentication looks and functions in your app, but it's good to hear what others think since FirebaseUI could save time with a simpler setup.
